version: '3.7'
services:
  web:
    build: .
    ports:
      - 8080:5000
    environment:
      - SECRET_KEY=foo
      - SQL_DATABASE=bookingapp_dev
      - SQL_USER=bookingapp
      - SQL_PASSWORD=bookingapp
      - SQL_HOST=db
